### ISSUE TITLE
Notify user when a valid action has been completed

### ISSUE THREAD

**Issue by Geo-Bold** [Geo-Bold/Frontend-Mentor#9]
The app should notify the user once the save button has been pressed and an action successfully completed.

**Comment by gitclonegaurang** [comment]
Seems good can i work on it ?

**Comment by Geo-Bold** [comment]
Absolutely @gitclonegaurang!
>
This is what I had in mind
>
![Example feedback:](https://github.com/user-attachments/assets/e97bf57f-f6c0-465d-9ebf-fe490ee726ba)
>
One possible solution would be to provide a modal instance that can be invoked upon the successful completion of a user directive such as saving the profile page successfully. This instance would have to persist for only a short, ideally customizable duration and only allow the existence of a single modal instance at any one time.
>
Feel free to share your own idea for implementing user notifications.
